/*
 * Evan Robertson
 * November 5 2018
 * Uses various string methods
 */

/**
 *
 * @author evrob0095
 */
public class stringMethods extends javax.swing.JFrame {

    /**
     * Creates new form stringMethods
     */
    public stringMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        replaceLabel = new javax.swing.JLabel();
        compareLetterText2 = new javax.swing.JTextField();
        replaceButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        lengthLabel = new javax.swing.JLabel();
        lengthText = new javax.swing.JTextField();
        lengthButton = new javax.swing.JButton();
        capsLabel = new javax.swing.JLabel();
        capsText = new javax.swing.JTextField();
        capsButton = new javax.swing.JButton();
        fourCharLabel = new javax.swing.JLabel();
        fourCharText = new javax.swing.JTextField();
        replaceText = new javax.swing.JTextField();
        fourCharButton = new javax.swing.JButton();
        compareLabel = new javax.swing.JLabel();
        compareText1 = new javax.swing.JTextField();
        compareText2 = new javax.swing.JTextField();
        compareButton = new javax.swing.JButton();
        compareLetterLabel = new javax.swing.JLabel();
        compareLetterText1 = new javax.swing.JTextField();
        compareLetterButton = new javax.swing.JButton();
        foursixCharLabel = new javax.swing.JLabel();
        foursixCharText = new javax.swing.JTextField();
        foursixCharButton = new javax.swing.JButton();
        print = new javax.swing.JLabel();
        output = new javax.swing.JLabel();
        replaceText2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        replaceLabel.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 14)); // NOI18N
        replaceLabel.setText("replaces all A's in a string");
        jPanel1.add(replaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        compareLetterText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareLetterText2ActionPerformed(evt);
            }
        });
        jPanel1.add(compareLetterText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 20, -1));

        replaceButton.setText("Print");
        replaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(replaceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        titleLabel.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 18)); // NOI18N
        titleLabel.setText("String Methods");
        jPanel1.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, -1));

        lengthLabel.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 14)); // NOI18N
        lengthLabel.setText("Finds length of string");
        jPanel1.add(lengthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        lengthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthTextActionPerformed(evt);
            }
        });
        jPanel1.add(lengthText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 90, -1));

        lengthButton.setText("Print");
        lengthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthButtonActionPerformed(evt);
            }
        });
        jPanel1.add(lengthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        capsLabel.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 14)); // NOI18N
        capsLabel.setText("outputs string in all caps");
        jPanel1.add(capsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        capsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capsTextActionPerformed(evt);
            }
        });
        jPanel1.add(capsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 90, -1));

        capsButton.setText("Print");
        capsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(capsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        fourCharLabel.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 14)); // NOI18N
        fourCharLabel.setText("finds the 4th character of the string");
        jPanel1.add(fourCharLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        fourCharText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourCharTextActionPerformed(evt);
            }
        });
        jPanel1.add(fourCharText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 90, -1));

        replaceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceTextActionPerformed(evt);
            }
        });
        jPanel1.add(replaceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 90, -1));

        fourCharButton.setText("Print");
        fourCharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourCharButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fourCharButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        compareLabel.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 14)); // NOI18N
        compareLabel.setText("Compare two strings");
        jPanel1.add(compareLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        compareText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareText1ActionPerformed(evt);
            }
        });
        jPanel1.add(compareText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 90, -1));

        compareText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareText2ActionPerformed(evt);
            }
        });
        jPanel1.add(compareText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 90, -1));

        compareButton.setText("Print");
        compareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareButtonActionPerformed(evt);
            }
        });
        jPanel1.add(compareButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        compareLetterLabel.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 14)); // NOI18N
        compareLetterLabel.setText("Compare string and a Letter");
        jPanel1.add(compareLetterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        compareLetterText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareLetterText1ActionPerformed(evt);
            }
        });
        jPanel1.add(compareLetterText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 90, -1));

        compareLetterButton.setText("Print");
        compareLetterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareLetterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(compareLetterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        foursixCharLabel.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 14)); // NOI18N
        foursixCharLabel.setText("Finds the 4th to 6th characters of a string");
        jPanel1.add(foursixCharLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        foursixCharText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foursixCharTextActionPerformed(evt);
            }
        });
        jPanel1.add(foursixCharText, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 90, -1));

        foursixCharButton.setText("Print");
        foursixCharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foursixCharButtonActionPerformed(evt);
            }
        });
        jPanel1.add(foursixCharButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        print.setFont(new java.awt.Font("Zap Raygun V2.0", 0, 14)); // NOI18N
        print.setText("Print");
        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        output.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        output.setText("...");
        jPanel1.add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        replaceText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceText2ActionPerformed(evt);
            }
        });
        jPanel1.add(replaceText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 20, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compareLetterText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareLetterText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compareLetterText2ActionPerformed

    private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonActionPerformed
        //Variables
        String input;
        String input2;
        //Get text
        input = replaceText.getText();
        input2 = replaceText2.getText();
        //Output
        output.setText(input.replace("a", input2));
    }//GEN-LAST:event_replaceButtonActionPerformed

    private void lengthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthTextActionPerformed

    private void lengthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthButtonActionPerformed
        //Variables
        String input;
        //get text
        input = lengthText.getText();
        //output
        output.setText(String.valueOf(input.length()));
    }//GEN-LAST:event_lengthButtonActionPerformed

    private void capsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capsTextActionPerformed

    private void capsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsButtonActionPerformed
        //Variables
        String input;
        //get text
        input = capsText.getText();
        //output
        output.setText(input.toUpperCase());
    }//GEN-LAST:event_capsButtonActionPerformed

    private void fourCharTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourCharTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourCharTextActionPerformed

    private void replaceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceTextActionPerformed

    private void fourCharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourCharButtonActionPerformed
        //Variables
        String input;
        //Get text
        input = fourCharText.getText();
        //output
        output.setText(String.valueOf(input.charAt(3)));
    }//GEN-LAST:event_fourCharButtonActionPerformed

    private void compareText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compareText1ActionPerformed

    private void compareText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compareText2ActionPerformed

    private void compareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareButtonActionPerformed
        //Variables
        String input1;
        String input2;
        //get text
        input1 = compareText1.getText();
        input2 = compareText2.getText();
        //output
        if(input1.equalsIgnoreCase(input2)) {
        output.setText("They are the same!");
        }
        else {
        output.setText("These are two different strings");
        }
    }//GEN-LAST:event_compareButtonActionPerformed

    private void compareLetterText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareLetterText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compareLetterText1ActionPerformed

    private void compareLetterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareLetterButtonActionPerformed
        //variables
        String input1;
        String input2;
        //get text
        input1 = compareLetterText1.getText();
        input2 = compareLetterText2.getText();
        //output
        if (input1.contains(input2)) {
        output.setText("The string includes a(n) " + input2);
        }
        else {
        output.setText("The string doesn't include a(n) " + input2);
        }
    }//GEN-LAST:event_compareLetterButtonActionPerformed

    private void foursixCharTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foursixCharTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foursixCharTextActionPerformed

    private void foursixCharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foursixCharButtonActionPerformed
        //Variables
        String input;
        //get text
        input = foursixCharText.getText();
        //output
        output.setText("The 4th to 6th values are " + input.charAt(3) +", " + input.charAt(4) + " and "+ input.charAt(5));
    }//GEN-LAST:event_foursixCharButtonActionPerformed

    private void replaceText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceText2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stringMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capsButton;
    private javax.swing.JLabel capsLabel;
    private javax.swing.JTextField capsText;
    private javax.swing.JButton compareButton;
    private javax.swing.JLabel compareLabel;
    private javax.swing.JButton compareLetterButton;
    private javax.swing.JLabel compareLetterLabel;
    private javax.swing.JTextField compareLetterText1;
    private javax.swing.JTextField compareLetterText2;
    private javax.swing.JTextField compareText1;
    private javax.swing.JTextField compareText2;
    private javax.swing.JButton fourCharButton;
    private javax.swing.JLabel fourCharLabel;
    private javax.swing.JTextField fourCharText;
    private javax.swing.JButton foursixCharButton;
    private javax.swing.JLabel foursixCharLabel;
    private javax.swing.JTextField foursixCharText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lengthButton;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JTextField lengthText;
    private javax.swing.JLabel output;
    private javax.swing.JLabel print;
    private javax.swing.JButton replaceButton;
    private javax.swing.JLabel replaceLabel;
    private javax.swing.JTextField replaceText;
    private javax.swing.JTextField replaceText2;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
